"""HNSW index chunk.embedding

Revision ID: 3c43fc47684f
Revises: dc7b9ecc86c5
Create Date: 2026-07-20 12:38:03.420601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c43fc47684f'
down_revision: Union[str, Sequence[str], None] = 'dc7b9ecc86c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('chunk_embedding_hnsw_index', 'chunk_table', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_l2_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('chunk_embedding_hnsw_index', table_name='chunk_table', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_l2_ops'})
    # ### end Alembic commands ###
