"""empty message

Revision ID: af6c88f0bd44
Revises: a358ffa8159b
Create Date: 2026-07-20 07:49:52.290967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'af6c88f0bd44'
down_revision: Union[str, Sequence[str], None] = 'a358ffa8159b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='docstatusenum',
        new_values=['QUEUED', 'CHUNKED', 'PROCESSED', 'FAILED'],
        affected_columns=[TableReference(table_schema='public', table_name='document_table', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='docstatusenum',
        new_values=['QUEUED', 'PROCESSING', 'CHUNKED', 'READY', 'FAILED'],
        affected_columns=[TableReference(table_schema='public', table_name='document_table', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
