"""empty message

Revision ID: dc7b9ecc86c5
Revises: af6c88f0bd44
Create Date: 2026-07-20 12:15:39.536573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7b9ecc86c5'
down_revision: Union[str, Sequence[str], None] = 'af6c88f0bd44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_table', sa.Column('total_token', sa.Integer(), nullable=True))
    op.add_column('document_table', sa.Column('estimated_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_table', 'estimated_cost')
    op.drop_column('document_table', 'total_token')
    # ### end Alembic commands ###
